INSERT INTO tege_param_estructgeograf (egedsdescripcionnivel, egefecreacion, egefemodificacion , egeidnivel, egedsnombrenivel , egecdusuariocreacion , egecdusuariomodifica ) VALUES('PAIS','2021-11-29', '2021-11-29',1,'PAIS','jc',NULL);
INSERT INTO tege_param_estructgeograf (egedsdescripcionnivel, egefecreacion, egefemodificacion , egeidnivel, egedsnombrenivel , egecdusuariocreacion , egecdusuariomodifica ) VALUES('DEPARTAMENTO','2021-11-29', '2021-11-29',2,'DEPARTAMENTO','jc',NULL);
INSERT INTO tege_param_estructgeograf (egedsdescripcionnivel, egefecreacion, egefemodificacion , egeidnivel, egedsnombrenivel , egecdusuariocreacion , egecdusuariomodifica ) VALUES('PROVINCIA','2021-11-29', '2021-11-29',3,'PROVINCIA','jc',NULL);
INSERT INTO tege_param_estructgeograf (egedsdescripcionnivel, egefecreacion, egefemodificacion , egeidnivel, egedsnombrenivel , egecdusuariocreacion , egecdusuariomodifica ) VALUES('MUNICIPIO','2021-11-29', '2021-11-29',4,'MUNICIPIO','jc',NULL);


INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('BOLIVIA', 1,null, null, null, null, null, null, null, null );

INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('BENI', 2,1, null, null, null, null, null, null, null );INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('PANDO', 2,1,null, null, null, null, null, null, null);
                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('SANTA CRUZ', 2,1,null, null, null, null, null, null, null);

                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('PROVINCIA DE CERCADO', 3,2,null, null, null, null, null, null, null);
                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('PROVINCIA DE ITEÑEZ', 3,2,null, null, null, null, null, null, null);
                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('PROVINCIA DE MAMORE', 3,2,null, null, null, null, null, null, null);

                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('PROVINCIA DE ABUNA', 3,3,null, null, null, null, null, null, null);
                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('PROVINCIA DE MADRE DE DIOS', 3,3,null, null, null, null, null, null, null);
                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('PROVINCIA DE MANURIPI', 3,3,null, null, null, null, null, null, null);

                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('PROVINCIA DE ANDRES IBAÑEZ', 3,4,null, null, null, null, null, null, null);
                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('PROVINCIA DE ANGEL SANDOVAL', 3,4,null, null, null, null, null, null, null);
                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('PROVINCIA DE CHIQUITOS', 3,4,null, null, null, null, null, null, null);

                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('SAN JAVIER', 4,5,null, null, null, null, null, null, null);
                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('TRINIDAD', 4,5,null, null, null, null, null, null, null);

                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('MAGDALENA', 4,6,null, null, null, null, null, null, null);
                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('BAURES', 4,6,null, null, null, null, null, null, null);
                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('HUACARAJE', 4,6,null, null, null, null, null, null, null);

                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('SAN JOAQUIN', 4,7,null, null, null, null, null, null, null);
                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('SAN RAMON', 4,7,null, null, null, null, null, null, null);
                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('PUERTO SILES', 4,7,null, null, null, null, null, null, null);

                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('SANTA ROSA DE ABUNA', 4,8,null, null, null, null, null, null, null);
                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('INGAVI', 4,8,null, null, null, null, null, null, null);

                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('PUERTO GONZALO MORENO', 4,9,null, null, null, null, null, null, null);
                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('SAN LORENZO', 4,9,null, null, null, null, null, null, null);
                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('SENA', 4,9,null, null, null, null, null, null, null);

                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('PUERTO RICO', 4,10,null, null, null, null, null, null, null);
                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('SAN PEDRO', 4,10,null, null, null, null, null, null, null);
                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('FILADELFIA', 4,10,null, null, null, null, null, null, null);

                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('SANTA CRUZ DE LA SIERRA', 4,11,null, null, null, null, null, null, null);
                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('COTOCA', 4,11,null, null, null, null, null, null, null);
                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('AYACUCHO', 4,11,null, null, null, null, null, null, null);
                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('LA GUARDIA', 4,11,null, null, null, null, null, null, null);
                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('EL TORNO', 4,11,null, null, null, null, null, null, null);

                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('SAN MATIAS', 4,12,null, null, null, null, null, null, null);

                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('SAN JOSE DE CHIQUITOS', 4,13,null, null, null, null, null, null, null);
                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('PAILON', 4,13,null, null, null, null, null, null, null);
                                                                                                                                                                                                                                                                                                        INSERT INTO tege_param_ubicacigeograf(gegdsnombreubicacion,gegidnivel, gegidubicacionpadre, gegcdcodigoiso, gegcdteleflargadist , gegcdcodigoubicacion , gegfecreacion , gegfemodificacion, gegcdusuariocreacion , gegcdusuariomodifica) VALUES('ROBORE', 4,13,null, null, null, null, null, null, null);
